require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/*'
    - '*.gemspec'
Naming/BlockForwarding:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
